name: kurban_json_view
description: "A Json To Widget Flutter project."
version: 1.0.0
repository: "https://github.com/Matkurban/json_viewer.git"
topics: [ widget ]

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


